### $Post: [/api/review/create] - Create review.
POST http://localhost:3000/api/review/create
content-type: application/json

{
	"name": "Test_Name",
	"title": "test_Title",
	"description": "test desc",
	"rating": 5
}


### $Delete: [/api/review/:id] - Delete review by id.
DELETE http://localhost:3000/api/review/:id


### $Get: [/api/review/byProduct/:productId] - Returns an array with found products.
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvbWVkdWRlQGR1ZGVzLmNvbSIsImlhdCI6MTY2ODc4NjU0N30.4pBn_HJjaWyVk5yOuDHk5PKWZLiOmywFFpwibA6QRds

GET  http://localhost:3000/api/review/byProduct/603c9d5ffa373014e6cd3ed2
{ }
