### $Post: [/api/review/create] - Create review.
POST http://localhost:3000/api/review/create
content-type: application/json

{
	"name": "Test_Name",
	"title": "test_Title",
	"description": "test desc",
	"rating": 5
}


### $Delete: [/api/review/:id] - Delete review by id.
DELETE http://localhost:3000/api/review/:id


### $Get: [/api/review/byProduct/:productId] - Кeturns an array with found products.
DELETE http://localhost:3000/api/review/byProduct/:productId
