### $Post: [/api/auth/register] - Register new user.
POST http://localhost:3000/api/auth/register
content-type: application/json

{
	"login": "somedude@dudes.com",
	"password": "somePassword"
}


### $Post: [/api/review/:id] - Login user.
POST  http://localhost:3000/api/auth/login
content-type: application/json

{
	"login": "somedude@dudes.com",
	"password": "somePassword1"
}
